from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "openspec" / "specs"
TARGET = ROOT / "docs" / "generated" / "requirements"

if TARGET.exists():
    shutil.rmtree(TARGET)
TARGET.mkdir(parents=True, exist_ok=True)

notice = (
    "> **Generated view. Do not edit this file.** "
    "The canonical source is the corresponding file under `openspec/specs/`.\n\n"
)

if not SOURCE.exists():
    (TARGET / "index.md").write_text(
        "# Requirements\n\nOpenSpec has not been initialized or contains no current specs yet.\n",
        encoding="utf-8",
    )
else:
    markdown_files = list(SOURCE.rglob("*.md"))
    if not markdown_files:
        (TARGET / "index.md").write_text(
            "# Requirements\n\nNo current Markdown specs are present.\n",
            encoding="utf-8",
        )
    for src in markdown_files:
        rel = src.relative_to(SOURCE)
        dst = TARGET / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(notice + src.read_text(encoding="utf-8"), encoding="utf-8")

print(f"Mirrored OpenSpec docs to {TARGET}")
